services:
  # Layanan Database (MySQL)
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: face_attendance
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql-data:/var/lib/mysql

  # Layanan PHP & Apache
  php-apache:
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - "8080:80" # Akses web dari browser melalui http://localhost:8080
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  # Layanan API Python
  python-api:
    build:
      context: .
      dockerfile: python.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./faces:/app/faces
    depends_on:
      - db

  # Layanan phpMyAdmin (Baru Ditambahkan)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80" # Akses dari browser melalui http://localhost:8081
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db